### Plus
GET http://localhost:8080/calculator/plus?num1=45&num2=20

### Minus
GET http://localhost:8080/calculator/minus?num1=45&num2=20

### Multiply
GET http://localhost:8080/calculator/multiply?num1=45&num2=20

### Divide
GET http://localhost:8080/calculator/divide?num1=45&num2=20